# Generated by Django 5.1.3 on 2025-01-25 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipeingredient_quantity_as_float'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipeingredient',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
